In [47]:
# import requests

# url = "http://www.camara.leg.br/cotas/Ano-2019.csv.zip"
# r = requests.get(url)

In [48]:
# file = open("Ano-2019.csv.zip", "wb")
# file.write(r.content)
# file.close()

In [49]:
# from zipfile import ZipFile

# zip_file = ZipFile("Ano-2019.csv.zip", 'r')

In [50]:
# zip_file.extract(member="Ano-2019.csv", path="reembolso-2019")

In [51]:
# zip_file.close()

In [52]:
import pandas as pd

In [53]:
DTYPE = {
    'txNomeParlamentar': str,
    'ideCadastro': str,
    'nuCarteiraParlamentar': str,
    'nuLegislatura': str,
    'sgUF': str,
    'sgPartido': str,
    'codLegislatura': str,
    'numSubCota': str,
    'txtDescricao': str,
    'numEspecificacaoSubCota': str,
    'txtDescricaoEspecificacao': str,
    'txtFornecedor': str,
    'txtCNPJCPF': str,
    'txtNumero': str,
    'indTipoDocumento': str,
    'datEmissao': str,
    'vlrDocumento': float,
    'vlrGlosa': str,
    'vlrLiquido': float,
    'numMes': str,
    'numAno': str,
    'numParcela': str,
    'txtPassageiro': str,
    'txtTrecho': str,
    'numLote': str,
    'numRessarcimento': str,
    'nuDeputadoId': str,
    'ideDocumento': str,
}

df_reembolso = pd.read_csv("reembolso-2019/Ano-2019.csv", sep=";", dtype=DTYPE)

In [54]:
df_reembolso.head(1)

,txNomeParlamentar,cpf,ideCadastro,nuCarteiraParlamentar,nuLegislatura,sgUF,sgPartido,codLegislatura,numSubCota,txtDescricao,...,numAno,numParcela,txtPassageiro,txtTrecho,numLote,numRessarcimento,vlrRestituicao,nuDeputadoId,ideDocumento,urlDocumento
0,LID.GOV-CD,NaN,NaN,NaN,2015,NaN,NaN,55,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,...,2019,0,NaN,NaN,1554246,NaN,NaN,2812,6738121,http://camara.leg.br/cota-parlamentar/nota-fis...

In [55]:
df_reembolso.sample(10)

,txNomeParlamentar,cpf,ideCadastro,nuCarteiraParlamentar,nuLegislatura,sgUF,sgPartido,codLegislatura,numSubCota,txtDescricao,...,numAno,numParcela,txtPassageiro,txtTrecho,numLote,numRessarcimento,vlrRestituicao,nuDeputadoId,ideDocumento,urlDocumento
145371,Aliel Machado,"6,908,052,923.00",178927,441,2019,PR,PSB,56,999,PASSAGEM AÉREA - RPA,...,2019,0,MAURICIO MARTINKOSKI,CWB/BSB,0,0,NaN,2915,1668456,NaN
112547,Rogério Peninha Mendonça,"16,513,703,034.00",160651,483,2019,SC,MDB,56,999,PASSAGEM AÉREA - RPA,...,2019,0,Rogério Peninha Mendonça,FLN/BSB,0,0,NaN,2244,1667978,NaN
282292,Otto Alencar Filho,"67,871,224,549.00",204573,206,2019,BA,PSD,56,3,COMBUSTÍVEIS E LUBRIFICANTES.,...,2019,0,NaN,NaN,1595567,NaN,NaN,3365,6832049,http://camara.leg.br/cota-parlamentar/nota-fis...
209096,Silvio Costa Filho,"3,500,720,439.00",204425,160,2019,PE,REPUBLICANOS,56,999,PASSAGEM AÉREA - RPA,...,2019,0,Silvio Costa Filho,BSB/REC,0,0,NaN,3341,1715343,NaN
91494,Marcon,"43,434,339,000.00",160535,507,2019,RS,PT,56,120,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,...,2019,0,NaN,NaN,1607986,NaN,NaN,2241,6859755,https://www.camara.leg.br/cota-parlamentar/doc...
17545,Daniel Almeida,"7,894,090,549.00",74060,188,2015,BA,PCdoB,55,11,SERVIÇOS POSTAIS,...,2019,0,NaN,NaN,0,0,NaN,1562,0,NaN
269452,Eduardo Bismarck,"61,882,577,353.00",204541,93,2019,CE,PDT,56,999,PASSAGEM AÉREA - RPA,...,2019,0,HELOISA MEDEIROS DINIZ,VIX/BSB,0,0,NaN,3396,1718523,NaN
146139,Diego Garcia,"4,702,291,955.00",178929,447,2015,PR,PODE,55,123,"PASSAGENS TERRESTRES, MARÍTIMAS OU FLUVIAIS",...,2019,0,NaN,NaN,1568353,NaN,NaN,3043,6764773,https://www.camara.leg.br/cota-parlamentar/doc...
60925,Arnaldo Jardim,"4,197,807,856.00",141391,339,2019,SP,CIDADANIA,56,10,TELEFONIA,...,2019,0,NaN,NaN,1633967,NaN,NaN,1786,6918938,NaN
57555,Cristiano Vale,"33,096,473,234.00",135054,25,2019,PA,PL,56,999,PASSAGEM AÉREA - RPA,...,2019,0,Cristiano Vale,BSB/BEL,0,0,NaN,3201,1709069,NaN

In [56]:
filtro_partido_null = df_reembolso.cpf.isna()
# filtro_partido_null = df_reembolso['sg-Partido'].isna()

df_reembolso.loc[filtro_partido_null, "cpf"] = "0000000"

In [57]:
df_reembolso.head()

,txNomeParlamentar,cpf,ideCadastro,nuCarteiraParlamentar,nuLegislatura,sgUF,sgPartido,codLegislatura,numSubCota,txtDescricao,...,numAno,numParcela,txtPassageiro,txtTrecho,numLote,numRessarcimento,vlrRestituicao,nuDeputadoId,ideDocumento,urlDocumento
0,LID.GOV-CD,0000000,NaN,NaN,2015,NaN,NaN,55,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,...,2019,0,NaN,NaN,1554246,NaN,NaN,2812,6738121,http://camara.leg.br/cota-parlamentar/nota-fis...
1,LID.GOV-CD,0000000,NaN,NaN,2019,NaN,NaN,56,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,...,2019,0,NaN,NaN,1570078,NaN,NaN,2812,6769606,http://camara.leg.br/cota-parlamentar/nota-fis...
2,LID.GOV-CD,0000000,NaN,NaN,2019,NaN,NaN,56,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,...,2019,0,NaN,NaN,1570503,NaN,NaN,2812,6771099,http://camara.leg.br/cota-parlamentar/nota-fis...
3,LID.GOV-CD,0000000,NaN,NaN,2019,NaN,NaN,56,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,...,2019,0,NaN,NaN,1579375,NaN,NaN,2812,6793690,http://camara.leg.br/cota-parlamentar/nota-fis...
4,LID.GOV-CD,0000000,NaN,NaN,2019,NaN,NaN,56,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,...,2019,0,NaN,NaN,1590980,NaN,NaN,2812,6821674,http://camara.leg.br/cota-parlamentar/nota-fis...

In [58]:
# df_reembolso["datEmissao"]

In [59]:
df_reembolso["datEmissao"] = pd.to_datetime(df_reembolso["datEmissao"], format="%Y-%m-%d")

In [60]:
# df_reembolso.set_index("datEmissao").loc["2019-01-01":"2019-04-30"]
# wd = {
#     0: "seg",
#     1: "ter",
# }

# df_reembolso["datEmissao"].dt.dayofweek < 5

In [61]:
df_reembolso["txtCNPJCPF"] = df_reembolso["txtCNPJCPF"].str.replace(r'\D', '', regex=True)

In [62]:
df_reembolso["txtCNPJCPF"]

0         03713903000108
1         03713903000108
2         03713903000108
3         03713903000108
4         03713903000108
               ...
288761    02012862000160
288762       00722772700
288763    02012862000160
288764    00000000000006
288765    09602675000185
Name: txtCNPJCPF, Length: 288766, dtype: object

In [63]:
df_reembolso.txtDescricao.value_counts(normalize=True).sort_values(ascending=False).to_frame().head(10)

                                                    txtDescricao
PASSAGEM AÉREA - RPA                                        0.28
COMBUSTÍVEIS E LUBRIFICANTES.                               0.22
SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO                   0.11
MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE P...          0.08
TELEFONIA                                                   0.08
FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR                  0.06
SERVIÇOS POSTAIS                                            0.05
DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.                        0.04
LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES               0.02
HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO F...          0.02

In [64]:
df_reembolso["vlrLiquido"].describe()

count   288,766.00
mean        712.20
std       2,091.95
min      -7,821.20
25%          48.98
50%         184.82
75%         689.94
max     145,140.00
Name: vlrLiquido, dtype: float64

In [65]:
# filtro_vlr_max = df_reembolso.vlrLiquido == df_reembolso.vlrLiquido.max()

filtro_cat_alim = df_reembolso.txtDescricao == 'FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR'
filtro_vlr_max = df_reembolso.vlrLiquido > 5000

df_reembolso[(filtro_cat_alim) & (filtro_vlr_max)]

,txNomeParlamentar,cpf,ideCadastro,nuCarteiraParlamentar,nuLegislatura,sgUF,sgPartido,codLegislatura,numSubCota,txtDescricao,...,numAno,numParcela,txtPassageiro,txtTrecho,numLote,numRessarcimento,vlrRestituicao,nuDeputadoId,ideDocumento,urlDocumento
152,LIDERANÇA DO PARTIDO REPUBLICANO DA ORDEM SOCIAL,0000000,NaN,NaN,2019,NaN,NaN,56,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,...,2019,0,NaN,NaN,1661111,NaN,NaN,2865,6981848,http://camara.leg.br/cota-parlamentar/nota-fis...
159,LIDERANÇA DO PARTIDO REPUBLICANO DA ORDEM SOCIAL,0000000,NaN,NaN,2019,NaN,NaN,56,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,...,2019,0,NaN,NaN,1650383,NaN,NaN,2865,6956990,http://camara.leg.br/cota-parlamentar/nota-fis...
160,LIDERANÇA DO PARTIDO REPUBLICANO DA ORDEM SOCIAL,0000000,NaN,NaN,2019,NaN,NaN,56,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,...,2019,0,NaN,NaN,1581569,NaN,NaN,2865,6798895,http://camara.leg.br/cota-parlamentar/nota-fis...
164,LIDERANÇA DO PARTIDO REPUBLICANO DA ORDEM SOCIAL,0000000,NaN,NaN,2019,NaN,NaN,56,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,...,2019,0,NaN,NaN,1609922,NaN,NaN,2865,6864494,http://camara.leg.br/cota-parlamentar/nota-fis...
168,LIDERANÇA DO PARTIDO REPUBLICANO DA ORDEM SOCIAL,0000000,NaN,NaN,2019,NaN,NaN,56,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,...,2019,0,NaN,NaN,1636965,NaN,NaN,2865,6926450,http://camara.leg.br/cota-parlamentar/nota-fis...
264,LIDERANÇA DO PROGRESSISTAS,0000000,NaN,NaN,2019,NaN,NaN,56,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,...,2019,0,NaN,NaN,1651228,NaN,NaN,3461,6959055,https://www.camara.leg.br/cota-parlamentar/doc...
265,LIDERANÇA DO PROGRESSISTAS,0000000,NaN,NaN,2019,NaN,NaN,56,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,...,2019,0,NaN,NaN,1655704,NaN,NaN,3461,6969841,https://www.camara.leg.br/cota-parlamentar/doc...
266,LIDERANÇA DO PROGRESSISTAS,0000000,NaN,NaN,2019,NaN,NaN,56,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,...,2019,0,NaN,NaN,1663508,NaN,NaN,3461,6987099,https://www.camara.leg.br/cota-parlamentar/doc...
267,LIDERANÇA DO PSD,0000000,NaN,NaN,2015,NaN,NaN,55,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,...,2019,0,NaN,NaN,1558264,NaN,NaN,2725,6747304,https://www.camara.leg.br/cota-parlamentar/doc...
283,LIDERANÇA DO PSD,0000000,NaN,NaN,2019,NaN,NaN,56,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,...,2019,0,NaN,NaN,1616327,NaN,NaN,2725,6879754,https://www.camara.leg.br/cota-parlamentar/doc...

In [66]:
df_reembolso.groupby(['sgPartido', 'sgUF', 'txNomeParlamentar'])["vlrLiquido"].sum().sort_values(ascending=False).to_frame()

                                  vlrLiquido
sgPartido sgUF txNomeParlamentar
PP        RR   Hiran Gonçalves    542,487.76
MDB       AC   Jéssica Sales      537,322.05
PDT       RS   Afonso Motta       537,270.79
PCdoB     AC   Perpétua Almeida   536,138.75
MDB       AC   Flaviano Melo      520,071.45
...                                      ...
PSDB      MS   Geraldo Resende          1.40
PV        MA   SARNEY FILHO             1.25
DEM       MS   MANDETTA                 0.60
PCdoB     PE   LUCIANA SANTOS           0.49
PROS      RJ   FELIPE BORNIER      -1,675.06

[851 rows x 1 columns]

In [67]:
pd.options.display.float_format = '{:,.2f}'.format

df_reembolso.groupby(['txtCNPJCPF', 'txtFornecedor'])['vlrLiquido'].sum().sort_values(
    ascending=False
).to_frame()[:10]

                                                                 vlrLiquido
txtCNPJCPF     txtFornecedor
02012862000160 Cia Aérea - TAM                                24,702,018.72
07575651000159 Cia Aérea - GOL                                22,007,574.87
09296295000160 Cia Aérea - AZUL                                6,440,608.61
07319323000191 PANTANAL VEÍCULOS LTDA                          2,181,274.52
02012862000160 TAM LINHAS AEREAS S/A.                          1,172,126.78
02575829000148 Cia Aérea - AVIANCA                             1,136,178.65
23721017000133 T2 COMUNICACAO, VIDEO E PRODUCOES EIRELI - EPP  1,097,334.00
00000000000001 CELULAR FUNCIONAL                                 872,853.43
02558157000162 TELEFÔNICA BRASIL S.A. VIVO                       860,813.15
02610235000120 DMD Gestão Administrativa LTDA - ME               805,000.00

In [68]:
df_reembolso[['txtCNPJCPF', 'txtFornecedor']]

            txtCNPJCPF                          txtFornecedor
0       03713903000108                 CRISTIANE FERREIRA EPP
1       03713903000108                 CRISTIANE FERREIRA EPP
2       03713903000108                 CRISTIANE FERREIRA EPP
3       03713903000108                 CRISTIANE FERREIRA EPP
4       03713903000108  PANIFICADORA FERREIRA NETO LTDA - EPP
...                ...                                    ...
288761  02012862000160                        Cia Aérea - TAM
288762     00722772700             LUIZ FELIPE GOULART MARINS
288763  02012862000160                         LATAM AIRLINES
288764  00000000000006                                  RAMAL
288765  09602675000185              CARRY SERVIÇOS E LOCAÇÕES

[288766 rows x 2 columns]

In [69]:
DTYPE = {
    'cnpj': str,
}

df_empresas = pd.read_csv(
    '2019-11-19-companies.csv.xz', 
    compression='xz',
    dtype=DTYPE,  
)

In [70]:
pd.set_option('display.max_columns', None)

In [71]:
df_empresas.head(1)

,cnpj,partners,secondary_activities,latitude,longitude,opening,main_activity,neighborhood,share_capital,zip_code,main_activity_code,city_code,judicial_nature_code,additional_address_details,removed_from_simples_since,opened_in,opted_for_comples_in,situation_date,special_situation_date,fax_area_code,phone1_area_code,phone2_area_code,address_type,responsible_federative_entity,hq_or_subsidiary_code,address,situation_reason,city,legal_entity,city_abroad_name,trade_name,number,mei,simples,size,administrative_person_category,name,situation,special_situation,phone,type,state,last_updated
0,08771105000156,"[{""id"": 2, ""name"": ""MARLY MORAIS DA GAMA"", ""cn...",NaN,NaN,NaN,NaN,NaN,REALEZA,"10,000.00","36,900,000.00",5611201,4787,2062,KM 51,2016-12-31,2007-04-12,2016-01-01,2007-04-12,NaN,33 33331212,33 33331222,33 33312882,AVENIDA,NaN,1,VITORIA MINAS,0,MANHUACU,NaN,NaN,LANCHONETE E RESTAURANTE PEQUENO PRINCIPE,S/N,0,0,1,49,WERNER COMERCIAL DE ALIMENTOS LTDA,2,NaN,NaN,NaN,MG,NaN

In [73]:
df_final = df_reembolso.merge(
    df_empresas,
    how='left',
    left_on='txtCNPJCPF',
    right_on='cnpj'
)

In [74]:
df_final.head(1)

,txNomeParlamentar,cpf,ideCadastro,nuCarteiraParlamentar,nuLegislatura,sgUF,sgPartido,codLegislatura,numSubCota,txtDescricao,numEspecificacaoSubCota,txtDescricaoEspecificacao,txtFornecedor,txtCNPJCPF,txtNumero,indTipoDocumento,datEmissao,vlrDocumento,vlrGlosa,vlrLiquido,numMes,numAno,numParcela,txtPassageiro,txtTrecho,numLote,numRessarcimento,vlrRestituicao,nuDeputadoId,ideDocumento,urlDocumento,cnpj,partners,secondary_activities,latitude,longitude,opening,main_activity,neighborhood,share_capital,zip_code,main_activity_code,city_code,judicial_nature_code,additional_address_details,removed_from_simples_since,opened_in,opted_for_comples_in,situation_date,special_situation_date,fax_area_code,phone1_area_code,phone2_area_code,address_type,responsible_federative_entity,hq_or_subsidiary_code,address,situation_reason,city,legal_entity,city_abroad_name,trade_name,number,mei,simples,size,administrative_person_category,name,situation,special_situation,phone,type,state,last_updated
0,LID.GOV-CD,0000000,NaN,NaN,2015,NaN,NaN,55,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,0,NaN,CRISTIANE FERREIRA EPP,03713903000108,693,4,2019-01-16,111.30,0,111.30,1,2019,0,NaN,NaN,1554246,NaN,NaN,2812,6738121,http://camara.leg.br/cota-parlamentar/nota-fis...,03713903000108,"[{""id"": 2, ""name"": ""ANTERO FERREIRA NETO"", ""cn...",NaN,NaN,NaN,NaN,NaN,SOBRADINHO,"50,000.00","73,025,060.00","1,091,102.00","9,701.00","2,062.00",LOJA 01,NaN,2000-02-28,2018-01-01,2005-11-03,NaN,NaN,61 3873040,NaN,QUADRA,NaN,1.00,06 CL,0.00,BRASILIA,NaN,NaN,PAO DE SAL,07,0.00,1.00,3.00,49.00,PANIFICADORA FERREIRA NETO LTDA,2.00,NaN,NaN,NaN,DF,NaN

In [75]:
df_final[['txtCNPJCPF', 'cnpj']]

            txtCNPJCPF            cnpj
0       03713903000108  03713903000108
1       03713903000108  03713903000108
2       03713903000108  03713903000108
3       03713903000108  03713903000108
4       03713903000108  03713903000108
...                ...             ...
478162     00722772700             NaN
478163  02012862000160  02012862000160
478164  02012862000160  02012862000160
478165  00000000000006             NaN
478166  09602675000185             NaN

[478167 rows x 2 columns]

In [76]:
f = df_final.situation == 8 

df_final[f].shape

(291, 74)

In [77]:
df_final["datEmissao"] = pd.to_datetime(df_final["datEmissao"], format="%Y-%m-%d") 
df_final['situation_date'] = pd.to_datetime(df_final["situation_date"], format="%Y-%m-%d")

In [79]:
df_final[f].query('datEmissao > situation_date').groupby('txNomeParlamentar').agg({'ideCadastro': 'count', 'vlrLiquido': 'sum'}).sort_values(by='vlrLiquido', ascending=False).reset_index()

             txNomeParlamentar  ideCadastro  vlrLiquido
0              Gleisi Hoffmann           42   62,065.18
1                 Carlos Veras           10   11,396.40
2               Carla Zambelli            1    7,289.65
3               Darci de Matos            1    2,869.38
4           General Peternelli           22    2,805.31
5               Geovania de Sá            2    2,703.30
6               Lucas Redecker            8    2,308.40
7                  Enéias Reis            1    1,729.39
8                 Carlos Gomes            1    1,560.00
9                   José Nunes            1    1,510.40
10                Paulo Ganime            2    1,244.16
11           Haroldo Cathedral            1    1,195.85
12  Professora Dayane Pimentel            9    1,142.25
13    José Airton Félix Cirilo            4      702.78
14               Fábio Ramalho            1      500.00
15        Lafayette de Andrada            3      421.50
16              João H. Campos            1      353.82
17                 CELSO JACOB            1      280.00
18            Damião Feliciano            1      259.79
19              Luizianne Lins            2      117.80
20          Euclydes Pettersen            1      100.00
21          Toninho Wandscheer            1       80.00
22               Coronel Tadeu            1       77.70
23             Carlos Chiodini            2       62.80
24              André de Paula            1       47.94
25           Alexandre Padilha            3       45.38
26               Túlio Gadêlha            1       42.00
27             Capitão Augusto            6       39.00
28         Coronel Chrisóstomo            1       30.35
29             Daniel Silveira            1       26.06
30         Sóstenes Cavalcante            1       26.00
31                 Jorge Solla            1       22.00
32          Hermes Parcianello            4       20.80
33       Alencar Santana Braga            1       16.52
34            Vanderlei Macris            1       15.00
35            Pompeo de Mattos            2       15.00
36              Fernando Borja            1       15.00
37                   Abou Anni            2       10.40